#ifndef _BOOST_SPIRIT_CONFIG_HPP
#define _BOOST_SPIRIT_CONFIG_HPP

#define BOOST_SPIRIT_DEBUG
#define BOOST_SPIRIT_USE_PHOENIX_V3
//#define BOOST_SPIRIT_LEXERTL_DEBUG
#define BOOST_SPIRIT_DEBUG_PRINT_SOME 80


#endif //_BOOST_SPIRIT_CONFIG_HPP
